# configs/outdoor_cr16_enhanced_data.yaml - Outdoor 1/16 configuration supporting 32×64 data (moderate difficulty)
model:
  name: CRLSTMNet
  spatial:
    res_blocks: 5                    # Keep 5 residual blocks
    channels: 40                     # Keep 40 channels
    latent_dim_high: 320             # High-dimensional features 320
    latent_dim_low: 80               # Low-dimensional features 80
    negative_slope: 0.3
    output_activation: linear
  temporal:
    layers: 3                        # 3 LSTM layers for outdoor complexity
    bidirectional: false
  sequence:
    T: 18                           # Moderate sequence length

training:
  batch_size: 12                     # Moderate batch_size
  num_workers: 0
  amp: true
  grad_clip: 1.0
  optimizer: adamw
  weight_decay: 1e-4
  pin_memory: true
  persistent_workers: false
  drop_last: false

  # Advanced training configuration
  gradient_accumulation_steps: 2     # Effective batch size = 12*2 = 24
  use_onecycle: true
  max_lr_factor: 4.0                 # Moderate learning rate factor

# 1/16 outdoor training stage settings (moderate training time)
stage0:
  epochs: 85                         # Moderate spatial pre-training
  lr: 1e-3
  warmup_epochs: 14
  cosine: true
  validate_every: 10
  early_stop:
    patience: 20                     # Moderate patience value
    min_delta: 0.0002

  multi_scale: true
  scale_factors: [0.8, 1.0, 1.2]

stage1:
  epochs: 60                         # Moderate temporal training
  lr: 5e-4
  validate_every: 8
  early_stop:
    patience: 18
    min_delta: 0.0002
  latent_consistency_weight: 0.15

  temporal_regularization: 0.07      # Moderate temporal regularization
  use_temporal_consistency: true

stage2:
  epochs: 50                         # Moderate end-to-end training
  lr: 2e-4
  validate_every: 10
  early_stop:
    patience: 22
    min_delta: 0.0002

  lr_decay_factor: 0.5
  lr_decay_patience: 12
  use_cosine_restart: true

# 1/16 outdoor loss weights (moderate constraints)
loss:
  nmse: 1.0
  cos: 0.18                          # Moderate cosine similarity weight
  tsmooth: 0.07                      # Moderate temporal smoothness weight

  freq_domain: 0.10                  # Moderate frequency domain loss weight
  correlation: 0.15                  # Moderate correlation coefficient loss weight

data:
  root: F:\CRLSTMNet\data\cost2100
  indoor_path: outdoor_20slots
  pdiff_path: P_diff_T
  dataset_spec:
    prefix: H_user_t
    suffix: 32all.mat
    variable_name: Hur_down_t1
    train_split: 0.8
  split: outdoor
  snr: 30
  cr: 1/16                           # 1/16 compression ratio
  cr_rate: 0.0625
  cr_num: 64                         # 64 measurements
  speed: 30
  normalize: per_batch
  use_pdiff: false
  cache_data: true
  prefetch_factor: 2
  allow_dummy_data: false

  # 1/16 data processing configuration (balance performance and efficiency)
  stride: 8                          # Moderate overlap, balance sample count and diversity
  downsample_method: smart_avg       # Balance performance and speed

  data_validation:
    enabled: true
    energy_threshold_db: 2.5         # Moderate energy threshold
    correlation_threshold: 0.96      # Moderate reconstruction quality requirement

logging:
  project: crlstm_cost2100_outdoor_cr16_enhanced
  run_name: outdoor_cr16_T18_enhanced_data
  save_dir: ./checkpoints/outdoor_cr16_enhanced
  log_interval: 10
  save_top_k: 3
  max_val_batches: 80

device: cuda
seed: 2025
deterministic: false
benchmark: true

model_naming:
  dataset_type: outdoor
  compression_ratio: "1_16_T18_enhanced"
  include_timestamp: true

monitoring:
  use_tqdm: true
  save_metrics: true
  metrics_file: metrics_outdoor_cr16_enhanced.json
  save_learning_curves: true
  plot_frequency: 10

# 1/16 data augmentation (moderate intensity)
data_augmentation:
  enabled: true
  noise_std: 0.018                   # Moderate noise intensity
  channel_shuffle: true
  temporal_shift: true

architecture_enhancements:
  use_attention: false
  use_residual_connections: true
  use_channel_attention: true
  use_spatial_attention: false

# Complexity analysis configuration
analyze_complexity: true

# 1/16 advanced training techniques
advanced_training:
  use_ema: true
  ema_decay: 0.998                   # Moderate decay rate
  use_label_smoothing: false
  use_mixup: false
  lr_finder: false
  use_distillation: true
  teacher_temperature: 4.3          # Moderate distillation temperature
  distillation_alpha: 0.33          # Moderate distillation weight

resume:
  enabled: true
  checkpoint_path: null
  load_optimizer: true
  load_scheduler: true
  load_best_metric: true

# 1/16 Special Notes:
# - Moderate difficulty task, balance performance and training efficiency
# - Uses moderate settings with T=18 and stride=8
# - Loss weights and training strategies are all moderate configurations
# - smart_avg method balances information retention and processing speed

# Expected Performance (1/16):
# - NMSE(dB): -16 ~ -24 dB
# - ρ: 0.78 ~ 0.88
# - Training time: moderate, balancing efficiency and effectiveness